"""Initial migration

Revision ID: 5fd1c9956c6c
Revises: e11e530e00aa
Create Date: 2025-03-14 19:55:32.249573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd1c9956c6c'
down_revision: Union[str, None] = 'e11e530e00aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrr',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_userrr_email'), 'userrr', ['email'], unique=True)
    op.create_index(op.f('ix_userrr_name'), 'userrr', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userrr_name'), table_name='userrr')
    op.drop_index(op.f('ix_userrr_email'), table_name='userrr')
    op.drop_table('userrr')
    # ### end Alembic commands ###
